### ISSUE TITLE
디자인

### ISSUE THREAD

**Issue by hs-jun** [ghrl1121/Satisfactory_server#1]
![전용서버](https://user-images.githubusercontent.com/120368544/224052396-7a65ec5c-c8ac-459e-9b0e-78f45ca6b904.png)

**Comment by hs-jun** [comment]
포샵으로 한 거라 윈도우 환경 창 구성이랑 조금 다를 수 있습니다.
참고용으로만 봐주세요

**Comment by hs-jun** [comment]
경로 레이블 클릭하면 경로 설정 창 나오고
서버 버전 버튼 클릭하면 얼리 액세스 - 익스페리멘탈 전환 되는 식으로

**Comment by ghrl1121** [comment]
서버 경로는 ... 클릭했을떼를 이야기 하시는거 같은데...
아직까지 오픈하기는 폴더 선택을 배우지 아니해서 ...
그리고 전 자동 로딩이 좋더라고요 (설치하면 자동으로 나오는것(서버 경로)(얼리 따로 익스 따로 해두었어요))

**Comment by ghrl1121** [comment]
피드백을 받아 수정하였습니다 단지 클릭형은 ... 더 공부해서 수정하겠습니다
